add popularity
progwise/george-ai pull request #78
Opened 2023-09-13 05:24 UTC by TonySchroeder

close #77

2023-09-14 10:27 UTC, moncapitaine commented on apps/strapi-cms/src/api/summary-feedback/content-types/summary-feedback/lifecycles.ts
> +  console.log('popularity: ', popularity)
remove comment

2023-09-14 10:29 UTC, moncapitaine commented on apps/strapi-cms/src/api/summary-feedback/content-types/summary-feedback/lifecycles.ts
> +    if (vote === 'down') {
```suggestion
    else if (vote === 'down') { ... }
    else { console.warn('value ${vote} is not implemented for calculating the popularity, feedback.id)
```

Else it disappears if something goes wrong here.

2023-09-14 10:31 UTC, moncapitaine requested changes
Code duplication when calculating popularity cannot be accepted.

2023-09-15 06:36 UTC, TonySchroeder commented on apps/typesense-cli/src/rebuild.collection.ts
> +      const popularity = summaryFeedbacks.reduce((accumulator, feedback) => {
I would move the function after merging "add drop collection" to avoid unnecessarily complicated merge conflicts.

2023-09-18 07:01 UTC, moncapitaine approved these changes

2023-09-18 07:03 UTC, merged